modLoader="javafml"
license = "MIT license"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/tterrag1098/Blur/issues"
displayURL="https://github.com/tterrag1098/Blur/"
authors="tterrag"
logoFile="blur_logo.png"

[[mods]]
modId="blur"
version="${file.jarVersion}"
displayName="Blur"
description="Adds a blurry background when viewing GUIs"

[[dependencies.blur]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.blur]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"